package com.atlas.roots.service;

import com.atlas.roots.dao.IdeaNodeDao;
import com.atlas.roots.dao.SkillDao;
import com.atlas.roots.dao.SubNodeDao;
import com.atlas.roots.model.IdeaNode;
import com.atlas.roots.model.Skill;
import com.atlas.roots.model.SubNode;
import com.atlas.roots.model.User;

import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;

/**
 * Assembles a user's Roots state into a Markdown prompt that any LLM
 * can consume as context for a conversation.
 *
 * <h2>The thesis</h2>
 * <p>This is the feature that makes Roots a <em>context layer</em>, not
 * just a dashboard. The user clicks "copy as prompt", pastes into Claude
 * or ChatGPT, and the AI immediately knows who they are — their skills,
 * their toolkit, their recent thinking, their patterns — without the
 * user ever typing "I'm a designer who uses Figma and Notion."</p>
 *
 * <h2>Structure of the output</h2>
 * <p>The output is a single Markdown document with four sections:</p>
 * <ol>
 *   <li><b>Identity</b> — who the user is, 1-2 sentences synthesized from
 *       their strongest skills.</li>
 *   <li><b>Skills + toolkit</b> — each skill listed with its supporting
 *       subscriptions nested underneath. This is the most important
 *       section: it tells the AI <em>what</em> the user does and
 *       <em>with what tools</em>.</li>
 *   <li><b>Recent thinking</b> — up to 10 most-recently-edited Ideas, one
 *       line each. This surfaces "what the user is currently working
 *       through", which gives the AI a temporal anchor.</li>
 *   <li><b>Ecosystem snapshot</b> — monthly burn, total subs, active
 *       ideas. A single paragraph of quantitative context.</li>
 * </ol>
 *
 * <h2>Why Markdown, not JSON</h2>
 * <p>LLMs read Markdown fluently. A Markdown prompt can be pasted
 * directly into any chat interface — Claude, ChatGPT, Gemini, local
 * Ollama — and produces immediate results. JSON would require an API
 * integration on the receiving end. The whole point of copy-as-prompt
 * is that it works everywhere, immediately, with no integration.</p>
 *
 * <h2>Privacy posture</h2>
 * <p>The export is generated on-demand and returned to the user's
 * browser. No data is transmitted to any third party by Roots itself —
 * the user decides where to paste it. This keeps the privacy model
 * intact: data only leaves the user's machine when <em>they</em> send it.</p>
 */
public final class ContextExporter {

    /** Max Ideas shown in the "Recent thinking" section. */
    static final int RECENT_IDEAS_CAP = 10;

    /** Max tokens shown per skill in the identity line + toolkit. */
    static final int TOKENS_PER_SKILL_CAP = 5;

    private final SkillDao   skillDao;
    private final SubNodeDao subDao;
    private final IdeaNodeDao ideaDao;

    public ContextExporter(SkillDao skillDao, SubNodeDao subDao, IdeaNodeDao ideaDao) {
        this.skillDao = skillDao;
        this.subDao   = subDao;
        this.ideaDao  = ideaDao;
    }

    /**
     * Build the full context prompt for a user. Returns the Markdown
     * string, ready to be copied and pasted into any LLM conversation.
     *
     * @param user the user whose context to export
     * @param decryptor a function that decrypts a ciphertext description;
     *        callers pass in a reference to the server's decrypt helper
     *        so this class doesn't need to know about CryptoService
     */
    public String exportPrompt(User user, java.util.function.Function<String, String> decryptor) throws SQLException {
        List<Skill>   skills = skillDao.findByOwner(user.getId());
        List<SubNode> subs   = subDao.findByOwner(user.getId());
        List<IdeaNode> ideas = ideaDao.findByOwner(user.getId());
        Map<Long, List<Long>> subsBySkill = skillDao.subIdsBySkill(user.getId());
        Map<Long, SubNode>    subsById    = new HashMap<>();
        for (SubNode s : subs) subsById.put(s.getId(), s);

        StringBuilder out = new StringBuilder();

        // --- Frontmatter-style header so the pasting-into-Claude moment
        // produces a prompt that visibly reads as context, not a question.
        out.append("# Context: ").append(safeUsername(user)).append("\n\n");
        out.append("*Generated by Roots — a personal context layer. ")
           .append("This is who I am, what I use, and what I'm thinking about right now. ")
           .append("Use this as the grounding for our conversation.*\n\n");

        // --- Section 1: Identity
        out.append("## Identity\n\n");
        out.append(synthesizeIdentityLine(skills)).append("\n\n");

        // --- Section 2: Skills + toolkit
        out.append("## Skills and toolkit\n\n");
        if (skills.isEmpty()) {
            out.append("*No skills extracted yet. Scan a vault and re-extract to populate this section.*\n\n");
        } else {
            for (Skill skill : skills) {
                int pct = (int) Math.round(skill.getConfidence() * 100);
                out.append("### ").append(skill.getName())
                   .append(" *(").append(pct).append("% confidence, ")
                   .append(skill.getIdeaCount()).append(" supporting notes)*\n");
                // The token set gives the LLM vocabulary to work with.
                List<String> topTokens = capTokens(skill.getTokens());
                if (!topTokens.isEmpty()) {
                    out.append("Keywords: `").append(String.join("`, `", topTokens)).append("`.\n");
                }
                // Linked subs — the "what tools" half of the skill.
                List<Long> linkedSubIds = subsBySkill.getOrDefault(skill.getId(), List.of());
                if (!linkedSubIds.isEmpty()) {
                    out.append("Tools I use for this:\n");
                    for (Long subId : linkedSubIds) {
                        SubNode sub = subsById.get(subId);
                        if (sub == null) continue;
                        out.append("- **").append(sub.getName()).append("**")
                           .append(" (").append(sub.getCurrency()).append(" ")
                           .append(formatCost(sub.getMonthlyCost())).append("/mo)");
                        String desc = decryptor.apply(sub.getDescription());
                        if (desc != null && !desc.isBlank()) {
                            String trimmed = desc.length() > 140 ? desc.substring(0, 137) + "…" : desc;
                            out.append(" — ").append(trimmed.replace('\n', ' '));
                        }
                        out.append('\n');
                    }
                }
                out.append('\n');
            }
        }

        // --- Section 3: Recent thinking
        out.append("## Recent thinking\n\n");
        List<IdeaNode> recent = pickRecentIdeas(ideas);
        if (recent.isEmpty()) {
            out.append("*No recent ideas recorded.*\n\n");
        } else {
            out.append("*These are the notes I've been working on most recently, ordered by recency:*\n\n");
            for (IdeaNode idea : recent) {
                String desc = decryptor.apply(idea.getDescription());
                out.append("- **").append(idea.getName()).append("**");
                if (desc != null && !desc.isBlank()) {
                    String trimmed = desc.length() > 180 ? desc.substring(0, 177) + "…" : desc;
                    out.append(" — ").append(trimmed.replace('\n', ' '));
                }
                out.append('\n');
            }
            out.append('\n');
        }

        // --- Section 4: Ecosystem snapshot
        out.append("## Ecosystem snapshot\n\n");
        double monthlyBurn = subs.stream().mapToDouble(SubNode::getMonthlyCost).sum();
        out.append("I currently have **").append(subs.size()).append(" active subscriptions** ")
           .append("with a combined monthly spend of roughly **")
           .append(subs.isEmpty() ? "0" : "₹" + formatCost(monthlyBurn))
           .append("**. ")
           .append("My vault contains **").append(ideas.size()).append(" ideas** ")
           .append("across **").append(skills.size()).append(" skill clusters**. ")
           .append("When you respond, ground your suggestions in this actual context rather than generic advice.\n\n");

        // --- Footer — signals to the LLM how to use the block
        out.append("---\n");
        out.append("*End of context. Respond to any follow-up questions with this context in mind.*\n");

        return out.toString();
    }

    // -----------------------------------------------------------------
    //  Internal helpers
    // -----------------------------------------------------------------

    /**
     * Synthesize a one-line identity statement from the top skills.
     * Falls back to a generic line if no skills exist.
     */
    private String synthesizeIdentityLine(List<Skill> skills) {
        if (skills.isEmpty()) {
            return "I am a Roots user who has not yet extracted skills from their vault.";
        }
        List<String> topNames = new ArrayList<>();
        int cap = Math.min(4, skills.size());
        for (int i = 0; i < cap; i++) topNames.add(skills.get(i).getName());
        String joined = joinHumanly(topNames);
        return "I am someone whose thinking and work centres on " + joined + ". "
                + "What follows is a structured view of my skills, the tools I use, and what I've been working through recently.";
    }

    /** Cap a token list to TOKENS_PER_SKILL_CAP entries. */
    private static List<String> capTokens(List<String> tokens) {
        if (tokens == null) return List.of();
        return tokens.size() <= TOKENS_PER_SKILL_CAP ? tokens : tokens.subList(0, TOKENS_PER_SKILL_CAP);
    }

    /**
     * Pick the most-recently-edited ideas, capped at RECENT_IDEAS_CAP.
     * Uses last-touched as the recency signal.
     */
    private static List<IdeaNode> pickRecentIdeas(List<IdeaNode> ideas) {
        List<IdeaNode> sorted = new ArrayList<>(ideas);
        sorted.sort((a, b) -> {
            LocalDateTime la = a.getLastTouched() == null ? LocalDateTime.MIN : a.getLastTouched();
            LocalDateTime lb = b.getLastTouched() == null ? LocalDateTime.MIN : b.getLastTouched();
            return lb.compareTo(la);
        });
        return sorted.size() > RECENT_IDEAS_CAP ? sorted.subList(0, RECENT_IDEAS_CAP) : sorted;
    }

    /** "a, b, and c" — natural English list join. */
    static String joinHumanly(List<String> items) {
        if (items == null || items.isEmpty()) return "";
        if (items.size() == 1) return items.get(0);
        if (items.size() == 2) return items.get(0) + " and " + items.get(1);
        return String.join(", ", items.subList(0, items.size() - 1))
                + ", and " + items.get(items.size() - 1);
    }

    private static String safeUsername(User user) {
        return user == null || user.getUsername() == null ? "anonymous" : user.getUsername();
    }

    private static String formatCost(double monthlyCost) {
        if (monthlyCost == Math.floor(monthlyCost)) {
            return String.valueOf((long) monthlyCost);
        }
        return String.format("%.2f", monthlyCost);
    }
}
